### ISSUE TITLE
Add Swift package manager support

### ISSUE THREAD

**Issue by harpreetsandc** [relatedcode/ProgressHUD#119]
Trying to add SPM but it is not allowing it... how to do it?

**Comment by michaeleustace** [comment]
I think the tags don't follow semantic versioning: Latest is 13.6 rather than 13.6.0

**Comment by yo1995** [comment]
In the meantime, I guess we need to add the `master` branch or the specific commit, in order to use the latest version, until the author re-tag the release. @relatedcode Can you help to update the release number using semantic versioning? Thanks.

![image](https://user-images.githubusercontent.com/9660181/141668474-0f682d9c-be61-4c8a-ad73-e3e213bdec4f.png)

**Comment by relatedcode** [comment]
@harpreetsandc @michaeleustace @yo1995 Please check now. Thanks!

**Comment by yo1995** [comment]
Thanks! Verified working well.
